### PR TITLE
Add & Remove Functions for items

### PR DESCRIPTION
**Pull request by AlucardSanin**
Implement a function for adding a new task (add a new element to the array).
Implement a function for deleting a task (remove an element from the array).
Implement a function for editing task descriptions.

### CODE REVIEW

**Review by leonardodiasb — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi @AlucardSanin, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

mario_ladders

## Good points 👍 

 - No linter errors. ✔️
 - Using ES6 features. ✔️

## Aspects to improve ♻️

- [ ] It is nice that you used a `<span>` tag with a `contenteditable` attribute but it seems that you forgot to create a function to keep track of the task description editing. When a user edits the task it should persist and in your app, when the user makes any change and reload the page or delete other tasks, the task that was edited changes the description to its first description. Please implement the edit function.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by MahmoudBakr23 — COMMENTED** [review]
# Hi @AlucardSanin 😃, 

As much as I appreciate your hard work on this project, I'm afraid that I can't perform a review on this pull request.

## **Invalid Submission**

- Please fix the linters error 

_Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready._ 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

<hr>

_Invalid Code Review Request does not count into the code reviews limit._

**Comment by CollinsTatang** [comment]
Hi @AlucardSanin , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has the node_modules directory unignore

- [ ] Please ignore the `node_modules` directory

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by prolajumokeoni — COMMENTED** [review]
Hi @AlucardSanin, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has node modules committed to git, please fix this, this was introduced in your merge commit, see how to fix this issue[ here](https://stackoverflow.com/questions/50675829/remove-node-modules-from-git-in-vscode) 👍🏿 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by prolajumokeoni** [comment]
Hi @AlucardSanin, your `node_modules` files are still not ignored by git, please take out time to fix this 👍🏿
Screenshot_385

- You have five thousand files committed to git, please delete node_modules and make sure it is ignored by git, this shows you have some untracked files by git

**Comment by AlucardSanin** [comment]
> Hi @AlucardSanin, your `node_modules` files are still not ignored by git, please take out time to fix this 👍🏿 Screenshot_385
> 
> * You have five thousand files committed to git, please delete node_modules and make sure it is ignored by git, this shows you have some untracked files by git

Can you mark the submit as invalid so I can submit again?

**Comment by AlucardSanin** [comment]
> Hi @AlucardSanin, your `node_modules` files are still not ignored by git, please take out time to fix this 👍🏿 Screenshot_385
> 
> * You have five thousand files committed to git, please delete node_modules and make sure it is ignored by git, this shows you have some untracked files by git

Would you mind mark the request as invalid?

**Review by whiz25 — APPROVED** [review]
Hi @AlucardSanin , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

### Martin Afani
#### Slack: whiz25

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
